CREATE TABLE IF NOT EXISTS directors (
director_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
director_name varchar
);

ALTER TABLE film
ADD COLUMN director_id int REFERENCES directors(director_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;